### ISSUE TITLE
Issue: Incorrect Link Renaming with Aliases and Large Link Sets

### ISSUE THREAD

**Issue by 1nsp1r3rnzt** [Lemon695/obsidian-missing-link-file-creator#1]
Thanks for developing this plugin. It's a really interesting idea and has the potential to be a huge time-saver. I've encountered a couple of issues while testing it out:

1.  **Handling Aliased Links:** The plugin seems to have trouble with links that include aliases (i.e., display text). For example:

    `[[🔨 resources/📚 books/How Democracies Die by Steven Levitsky and Daniel Ziblatt|How Democracies Die by Steven Levitsky and Daniel Ziblatt]]`

    Instead of correctly identifying and linking to the target file ("How Democracies Die by Steven Levitsky and Daniel Ziblatt.md", or whatever the actual filename is), it appears to be including the `|` character and subsequent alias text in the generated link, resulting in wrong links.  It is creating files with the `|` in the filename along with following alias which is undesirable.

2.  **Incorrect Renaming with Many Links:** When processing a page with a large number of links (around 100 in my test case), the plugin appears to be incorrectly renaming some links.  I observed instances where multiple links were renamed to the *same* value, effectively pointing to the same link. This makes is challenging to fully rely on the plugin, as I'm concerned about potential data corruption due to incorrect link replacements.

I'm happy to provide more specific examples or test cases if that would be helpful. I'm running `Obsidian 1.8.4` on `Ubuntu`. Let me know if there's any information I can provide to assist in fixing it.

Thanks again for your work on this!

**Comment by Lemon695** [comment]
> Thanks for developing this plugin. It's a really interesting idea 和 has the potential to be a huge time-saver. I've encountered a couple of issues while testing it out:
> 
> 1. **Handling Aliased Links:** The plugin seems to have trouble with links that include aliases (i.e., display text). For example:
>    `[[🔨 resources/📚 books/How Democracies Die by Steven Levitsky and Daniel Ziblatt|How Democracies Die by Steven Levitsky and Daniel Ziblatt]]`
>    Instead of correctly identifying 和 linking to the target file ("How Democracies Die by Steven Levitsky 和 Daniel Ziblatt.md", or whatever the actual filename is), it appears to be including the `|` character 和 subsequent alias text in the generated link, resulting in wrong links. It is creating files with the `|` in the filename along with following alias which is undesirable.
> 2. **Incorrect Renaming with Many Links:** When processing a page with a large number of links (around 100 in my test case), the plugin appears to be incorrectly renaming some links.  I observed instances where multiple links were renamed to the _same_ value, effectively pointing to the same link. This makes is challenging to fully rely on the plugin, as I'm concerned about potential data corruption due to incorrect link replacements.
> 
> I'm happy to provide more specific examples or test cases if that would be helpful. I'm running `Obsidian 1.8.4` 于 `Ubuntu`. Let me know if there's any information I can provide to assist in fixing it.
> 
> Thanks again for your work on this!

Thank you very much for your feedback! The issues you've raised are extremely valuable for improving the plugin, and I will release updates to fix these problems as soon as possible.

**Comment by Lemon695** [comment]
@1nsp1r3rnzt Thank you very much for your feedback! 

In recent update (v1.0.6),the plugin currently supports creating multiple files from different link types in a single operation.

When scanning your notes, the plugin identifies different types of links that point to non-existent files:

Standard internal links: [[filename]]
Links with aliases: [[filename|alias]]
Links with paths: [[path/to/filename]]
Embedded links: ![[filename]]
Links in resource directories: [[resources/books/filename]]

If both ![[filename]] and [[resources/books/filename]] are found in your note and neither file exists, the plugin will create both files independently. The confirmation dialog will list all files to be created, allowing you to select which ones you want to generate.

**Comment by 1nsp1r3rnzt** [comment]
Thank you for the update!. it seems to be working smoothly, and I also appreciate the addition of the new progress bar. It would be fantastic if you could add a feature that allows users to create pages from selected links through the right click menu.

For example, it would be helpful to bunch select multiple links for pages that haven't been created yet and then right-click to generate all of them at once.

**Comment by Lemon695** [comment]
> Thank you for the update! It seems to be working smoothly, 和 I appreciate the addition of the new progress bar. It would be fantastic if you could add a feature that allows users to create pages from selected links through the right-click menu.
> 
> For example, it would be helpful to select multiple links for pages that haven't been created yet and then right-click to generate all of them at once.
> 
> Edit: when the plugin creates aliases, it prevents the Templator from generating a template note. Would it be possible to disable aliases in the settings or merge it with the Templator note meta values? Example:
> 
> * [[🔨 resources/📚 books/Book name by author|Book name by author]]
> 
> The Templator sets the template for any new note in the 📚 books folder, but it doesn't get triggered due to the addition of aliases.

@1nsp1r3rnzt  Thank you for your suggestions! I’ll analyze these issues and aim to include these optimizations in the next version.

**Comment by Lemon695** [comment]
> Thank you for the update! It seems to be working smoothly, 和 I appreciate the addition of the new progress bar. It would be fantastic if you could add a feature that allows users to create pages from selected links through the right-click menu.
> 
> For example, it would be helpful to select multiple links for pages that haven't been created yet and then right-click to generate all of them at once.
> 
> Edit: when the plugin creates aliases, it prevents the Templator from generating a template note. Would it be possible to disable aliases in the settings or merge it with the Templator note meta values? Example:
> 
> * [[🔨 resources/📚 books/Book name by author|Book name by author]]
> 
> The Templator sets the template for any new note in the 📚 books folder, but it doesn't get triggered due to the addition of aliases.

@1nsp1r3rnzt 
Thank you for your feedback! I'm pleased to inform you that our newly released version 1.0.7 has already implemented most of the features you mentioned!

1. **Right-click menu for creating links** - The new version now supports creating files from selected unresolved links through the right-click context menu.
    
2. **Alias integration with Templater** - We've addressed the compatibility issue between aliases and Templater. The new version offers enhanced alias handling options, allowing you to choose how aliases are processed in templates, including merge or skip options.
    
3. **Rule system** - You can now create rules to automatically apply specific templates based on file path patterns (like the "📚 books" folder in your example).

**Comment by 1nsp1r3rnzt** [comment]
Thank you for the update. I tested the right-click menu, and it seems to be creating all links.

However, I am still experiencing issues with the Templater plugin when creating mass links with specific templates. When the plugin is used to create pages for multiple links, the template ends up with the wrong title.

Here are the example links I have created:

- [[🔨 resources/📚 books/book a by A. A. Milne|book a by A. A. Milne]]
- [[🔨 resources/📚 books/book b by William Butler Yeats|book b by William Butler Yeats]]
- [[🔨 resources/📚 books/book c by ab|book c by ab]]

Currently, the Templater template for each book has a line that assigns the title as follows:

```javascript
let title = tp.file.title;
```

The issue arises when the template is applied. The title assigned to the template for "book b" becomes some other title, such as "book a." It seems that it is pulling the title from one of the previous links instead of using its own title.

I am unsure why the title from one link is appearing in another's template, and I would greatly appreciate your thoughts on it. Thank you for your continuous updates.
